name: Compilation

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        kind: [static, shared]
    
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@dev
      - name: Configuration
        env:
          XMAKE_ROOT: y
        run: |
          xmake config -m release -k ${{ matrix.kind }} --tests=y -y
      - name: Build
        env:
          XMAKE_ROOT: y
        run: |
          xmake build
      - name: Tests
        env:
          XMAKE_ROOT: y
        run: |
          xmake run tests


